# Generated by Django 4.0.3 on 2023-01-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_answer_modify_data_question_modify_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='modify_data',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modify_data',
            new_name='modify_date',
        ),
    ]
